      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 20,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'us.api.blizzard.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _headerFilter: /^(?:Authorization|Proxy-Authorization|Cookie)$/i,
      _currentRequest: [Circular *1],
      _currentUrl: 'https://us.api.blizzard.com/data/wow/search/recipe?namespace=static-us&locale=es_MX&access_token=USuvB0NZlS66NC7XCMjq836zN5vjKH4lwI&name.es_MX=Frasco+de+poder+aislado&_page=1&_pageSize=1',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
      'x-trace-spanid': '18b9fcd3-1850-c342-60a0-beb281ff57c6',
      validateStatus: [Function: validateStatus],
      'x-trace-parentspanid': '18b9fcd3-1850-c312-60a0-beb281ff57c6',
      transformResponse: [Array],
    status: 404,
    statusText: 'Not Found',
      'x-frame-options': 'SAMEORIGIN',
      timeout: 0,
      'x-content-type-options': 'nosniff',
    headers: Object [AxiosHeaders] {
      server: 'blizzard'
      date: 'Sat, 20 Jun 2026 08:56:18 GMT',
    config: [Object: null prototype] {
      connection: 'keep-alive',
    },
      'content-length': '0',
      transitional: [Object],
      'x-trace-traceid': '382ecf2d-e2d3-3b7b-b7a6-16482d7967e1',
      maxContentLength: -1,
      traceparent: '00-343a7531e43a7b5065cecbdef5f09cd7-7b00f8336b55300a-01',
      maxBodyLength: -1,
      adapter: [Array],
      xsrfCookieName: 'XSRF-TOKEN',
      env: [Object],
      transformRequest: [Array],
      xsrfHeaderName: 'X-XSRF-TOKEN',
      _events: [Object: null prototype],
      allowAbsoluteUrls: true,
      _maxListeners: undefined,
      headers: [Object [AxiosHeaders]],
      destroyed: true,
      _eventsCount: 7,
      params: [Object],
      outputData: [],
      data: undefined
      outputSize: 0,
      method: 'get',
    },
      writable: true,
      _last: true,
      url: 'https://us.api.blizzard.com/data/wow/search/recipe',
    request: <ref *1> ClientRequest {
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      joinDuplicateHeaders: undefined,
      path: '/data/wow/search/recipe?namespace=static-us&locale=es_MX&access_token=USuvB0NZlS66NC7XCMjq836zN5vjKH4lwI&name.es_MX=Frasco+de+poder+aislado&_page=1&_pageSize=1',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /data/wow/search/recipe?namespace=static-us&locale=es_MX&access_token=USuvB0NZlS66NC7XCMjq836zN5vjKH4lwI&name.es_MX=Frasco+de+poder+aislado&_page=1&_pageSize=1 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.18.0\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: us.api.blizzard.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: false,
}
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'us.api.blizzard.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  },
  status: 404
